version: '3.4'

services:
  ollim.bot:
    image: ${DOCKER_REGISTRY-}ollimbot
    build:
      context: .
      dockerfile: Ollim.Bot/Dockerfile
    ports:
        - 1111:1111
    environment:
        - ASPNETCORE_ENVIRONMENT=Production